// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGC43NMU9UJftAJ7OIBS-1q35pIUIssCE',
    appId: '1:368966349706:web:3a79dbd823df7f31464e73',
    messagingSenderId: '368966349706',
    projectId: 'nexaurquidijosue',
    authDomain: 'nexaurquidijosue.firebaseapp.com',
    storageBucket: 'nexaurquidijosue.firebasestorage.app',
    measurementId: 'G-G28S1SEF8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbMDTiFjg6k1w7LAsW__qAP4yCW4i-sBU',
    appId: '1:368966349706:android:0a0653e8ba1a6c2e464e73',
    messagingSenderId: '368966349706',
    projectId: 'nexaurquidijosue',
    storageBucket: 'nexaurquidijosue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5_10SPfYsF-VIBNnRnrZ6fl-xgODgbxM',
    appId: '1:368966349706:ios:88b3898989af5e8b464e73',
    messagingSenderId: '368966349706',
    projectId: 'nexaurquidijosue',
    storageBucket: 'nexaurquidijosue.firebasestorage.app',
    iosBundleId: 'com.example.examenmovilsw1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5_10SPfYsF-VIBNnRnrZ6fl-xgODgbxM',
    appId: '1:368966349706:ios:88b3898989af5e8b464e73',
    messagingSenderId: '368966349706',
    projectId: 'nexaurquidijosue',
    storageBucket: 'nexaurquidijosue.firebasestorage.app',
    iosBundleId: 'com.example.examenmovilsw1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGC43NMU9UJftAJ7OIBS-1q35pIUIssCE',
    appId: '1:368966349706:web:36f7e0a1c6adf74e464e73',
    messagingSenderId: '368966349706',
    projectId: 'nexaurquidijosue',
    authDomain: 'nexaurquidijosue.firebaseapp.com',
    storageBucket: 'nexaurquidijosue.firebasestorage.app',
    measurementId: 'G-CMBGVTSEH1',
  );
}
